apiVersion: apps/v1
kind: Deployment
metadata:
  name: real-estate-frontend
  labels:
    app: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end
        image: 057494829841.dkr.ecr.eu-west-3.amazonaws.com/3-tier-for-frontend-assi
        ports:
        - containerPort: 4200
---
spec:
apiVersion: v1
kind: Service
metadata:
  name: real-estate-back-svc
spec:
  selector:
    app: backend-app
  ports:
    - port: 80
      targetPort: 4200
  type: LoadBalancer
